package net.javaguides.springboot.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;



//Adding @Entity Annotation to make this class as Entity class and Adding @Table Annotation to Create A table with name ="Atm"
@Entity
@Table(name="Atm")
public class Atm {
	
	
	
	//Adding @Id annotation to make that Id as Primary Key and will be AutoGenerated with increment 
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long AtmId;
	//Adding @Column annotation with name = "AtmName" here it will creates a column with our required name
	@Column(name="AtmName")
	private String AtmName;
	
	
	
	//Adding default constructor
	public Atm() {
		
	}
	
	
	
	//Generating getters and setters 
	public Atm(String atmName) {
		super();
		AtmName = atmName;
	}
	
	public Long getAtmId() {
		return AtmId;
	}
	public void setAtmId(Long atmId) {
		AtmId = atmId;
	}
	public String getAtmName() {
		return AtmName;
	}
	
	//Generating constuctor using fields
	public void setAtmName(String atmName) {
		AtmName = atmName;
	}
	
	

}
